Scaling
nikebless/mats-3-aligning-lms pull request #1
Opened 2022-11-16 16:40 UTC by AsaCooperStickland

make the project pip installable with 'poetry', and add a way to run a series of experiments and install the results, `src/main.py`.

2022-11-17 23:57 UTC, nikebless commented on src/main.py
> +        "--dataset-name",
BIG-Bench uses “task” instead of dataset, let’s stay consistent to it?

2022-11-17 23:59 UTC, nikebless commented on src/main.py
> +        type=str,
Also, how about supporting multiple tasks? Leave for next PR?

2022-11-18 00:03 UTC, mbalesni requested changes
Awesome stuff! Let’s do `dataset-name` —> task and optionally several tasks?

2022-11-18 13:42 UTC, AsaCooperStickland commented
made the suggested changes!

2022-11-22 11:40 UTC, nikebless commented
I wanted to add summary performance plots, but will leave it for later and merge now; it's been way too long!

2022-11-22 11:40 UTC, merged